---
title: "np_percent_cover"
author: "Joanna Tang"
date: "11/22/2018"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include = FALSE}
# Loading packages, read in data
library(tidyverse)
library(knitr)
library(kableExtra)
library(vegan)
np_2016_seedbank_master <- read_csv("np_2016_seedbank.csv")
np_percent_cover <- read_csv("np_percent_cover.csv")
metadata <- read_csv("metadata.csv")

```

```{r include = FALSE}

# Separate "Replicate" label into Replicate_Zone and Replicate_Number, join with species metadata, convert month and year to "date" column
percent_cover <- np_percent_cover %>% 
  mutate(Replicate_Zone = case_when(Replicate == "C1" ~ "C", Replicate == "C2" ~ "C", Replicate == "C3" ~ "C", Replicate == "T1" ~ "T", Replicate == "T2" ~ "T", Replicate == "T3" ~ "T", Replicate == "U1" ~ "U", Replicate == "U2" ~ "U", Replicate == "U3" ~ "U")) %>% 
  mutate(Replicate_Number = case_when(Replicate == "C1" ~ "1", Replicate == "C2" ~ "2", Replicate == "C3" ~ "3", Replicate == "T1" ~ "1", Replicate == "T2" ~ "2", Replicate == "T3" ~ "3", Replicate == "U1" ~ "1", Replicate == "U2" ~ "2", Replicate == "U3" ~ "3"))
percent_cover <- full_join(percent_cover, metadata) %>% 
  mutate(month_number = case_when(Month == "JANUARY" ~ 1, Month == "FEBRUARY" ~ 2, Month == "MARCH" ~ 3, Month == "APRIL" ~ 4, Month == "MAY" ~ 5, Month == "JUNE" ~ 6, Month == "JULY" ~ 7, Month == "AUGUST" ~ 8, Month == "SEPTEMBER" ~ 9, Month == "OCTOBER" ~ 10, Month == "NOVEMBER" ~ 11, Month == "DECEMBER" ~ 12)) %>% 
  mutate(date = paste(Year, month_number, "1", sep="-" ))
percent_cover$date = as.Date(percent_cover$date)

# Make separate dataframes for each site

ph1_percent_cover <- filter(percent_cover, Plot == "PH1")

ms_percent_cover <- filter(percent_cover, Plot == "MS")

rt_percent_cover <- filter(percent_cover, Plot == "RT")

tp_percent_cover <- filter(percent_cover, Plot == "TP")

wt1_percent_cover <- filter(percent_cover, Plot == "WT1")

wt2_percent_cover <- filter(percent_cover, Plot == "WT2")

cs_percent_cover <- filter(percent_cover, Plot == "CS")


```

# Phase 1

```{r echo = FALSE, message = FALSE, warning = FALSE}

# Aggregate PH1 data
ph1_percent_cover_summary <- ph1_percent_cover %>% 
  group_by(Species, date, Native_Status, Replicate_Zone) %>% 
  summarize(
    mean_percentage = mean(percent_cover)
    )

# Aggregate percentages
#ph1_line <- ggplot(ph1_percent_cover_summary, aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover", x = "Date", y = "Mean Percent Cover")
#ph1_line


# Percentages by zone
ph1_line_facet <- ggplot(ph1_percent_cover_summary, aes(x = date, y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover by Zone", x = "Date", y = "Mean Percent Cover") +
  facet_wrap(~Replicate_Zone)
ph1_line_facet

# Percentages by zone of species present in seeedbank
ph1_seed_only <- ggplot(filter(ph1_percent_cover_summary, Species == "JUBU" | Species == "FEPE" | Species == "COSU" | Species == "ERCA" | Species == "LYHY" | Species == "SYSU" | Species == "BAPI" | Species == "PSBR" | Species == "SIBE" | Species == "SPSP" | Species == "POMO" | Species == "SOOL" | Species == "ZEMU" | Species == "CYER" | Species == "EHER" | Species == "FRSA" | Species == "HEEC"), aes(x = factor(date), y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover of Seed Bank Species", x = "Date", y = "Mean Percent Cover", caption = "11/18 seed bank species present; \n\ transition most species-rich; \n\ note FEPE, SIBE, JUBU") +
  facet_wrap(~Replicate_Zone)
ph1_seed_only


# Percentages by zone of natives only
ph1_native <- ggplot(filter(ph1_percent_cover_summary, Native_Status == "N"), aes(x = factor(date), y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover of Natives by Zone", x = "Date", y = "Mean Percent Cover", caption = "Note ELMA, JUPA, ERVA, HOBR, SIBE, STPL") +
  facet_wrap(~Replicate_Zone)
ph1_native

# Percentages by zone of exotics only
ph1_exotic <- ggplot(filter(ph1_percent_cover_summary, Native_Status == "E"), aes(x = factor(date), y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover of Exotics by Zone", x = "Date", y = "Mean Percent Cover", caption = "Note FEPE, BRSP") +
  facet_wrap(~Replicate_Zone)
ph1_exotic

# Central zone percentages
#ph1_c_line <- filter(ph1_percent_cover, Replicate_Zone == "C") %>% 
  #group_by(Species, date, Native_Status) %>% 
  #summarize(
  #  mean_percentage = mean(percent_cover)
  #  ) %>%
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Central Zone", x = "Date", y = "Mean Percent Cover")
#ph1_c_line

# Transition zone percentages
#ph1_t_line <- filter(ph1_percent_cover, Replicate_Zone == "T") %>% 
  #group_by(Species, date, Native_Status) %>% 
  #summarize(
  #  mean_percentage = mean(percent_cover)
  #  ) %>%
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Transition Zone", x = "Date", y = "Mean Percent Cover")
#ph1_t_line

# Upland zone percentages
#ph1_u_line <- filter(ph1_percent_cover, Replicate_Zone == "U") %>% 
  #group_by(Species, date, Native_Status) %>% 
  #summarize(
    #mean_percentage = mean(percent_cover)
    #) %>%
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Transition Zone", x = "Date", y = "Mean Percent Cover")
#ph1_u_line


# Aggregate percentages of 12 indicative species
#ph1_12_line <- filter(ph1_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover of 12 Indicative Species", x = "Date", y = "Mean Percent Cover")
#ph1_12_line

# Aggregate percentages of 12 indicative species by zone
ph1_12_line_facet <- filter(ph1_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  ggplot(aes(x = factor(date), y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover of 12 Indicative Species by Zone", x = "Date", y = "Mean Percent Cover") +
  facet_wrap(~Replicate_Zone)
ph1_12_line_facet

# Central zone percentages of 12 indicative species
#ph1_c_12_line <- filter(ph1_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  #filter(Replicate_Zone == "C") %>% 
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover of 12 Indicative Species in Central Zone", x = "Date", y = "Mean Percent Cover")
#ph1_c_12_line

# Transition zone percentages of 12 indicative species
#ph1_t_12_line <- filter(ph1_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  #filter(Replicate_Zone == "T") %>% 
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover of 12 Indicative Species in Transition Zone", x = "Date", y = "Mean Percent Cover")
#ph1_t_12_line

# Upland zone percentages of 12 indicative species
#ph1_u_12_line <- filter(ph1_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  #filter(Replicate_Zone == "U") %>% 
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover of 12 Indicative Species in Upland Zone", x = "Date", y = "Mean Percent Cover")
#ph1_u_12_line


# Native vs. exotic
ph1_native <- ph1_percent_cover_summary %>% 
  group_by(Native_Status, date, Replicate_Zone) %>% 
  summarize(
    total = sum(mean_percentage)
  ) %>% 
  na.omit()

# Aggregate
#ph1_native_line <- ggplot(ph1_native, aes(x = date, y = total)) +
  #geom_line(aes(color = Native_Status, group = Native_Status)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover", x = "Date", y = "Mean Percent Cover")
#ph1_native_line

# Aggregate by zone
ph1_native_line_facet <- ggplot(ph1_native, aes(x = factor(date), y = total)) +
  geom_line(aes(color = Native_Status, group = Native_Status)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Native vs Exotic total cover", x = "Date", y = "total Percent Cover", caption = "Can see loose inverse relationship, \n\ invasives peak after natives") +
  facet_wrap(~Replicate_Zone)
ph1_native_line_facet

# Central zone
#ph1_c_native_line <- ggplot(filter(ph1_native, Replicate_Zone == "C"), aes(x = date, y = total)) +
  #geom_line(aes(color = Native_Status, group = Native_Status)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Central Zone", x = "Date", y = "Mean Percent Cover")
#ph1_c_native_line

# Transition zone
#ph1_t_native_line <- ggplot(filter(ph1_native, Replicate_Zone == "T"), aes(x = date, y = total)) +
  #geom_line(aes(color = Native_Status, group = Native_Status)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Transition Zone", x = "Date", y = "Mean Percent Cover")
#ph1_t_native_line

# Upland zone
#ph1_u_native_line <- ggplot(filter(ph1_native, Replicate_Zone == "U"), aes(x = date, y = total)) +
  #geom_line(aes(color = Native_Status, group = Native_Status)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Upland Zone", x = "Date", y = "Mean Percent Cover")
#ph1_u_native_line

```

# Mini South

```{r echo = FALSE, message = FALSE, warning = FALSE}

# Aggregate MS data
ms_percent_cover_summary <- ms_percent_cover %>% 
  group_by(Species, date, Native_Status, Replicate_Zone) %>% 
  summarize(
    mean_percentage = mean(percent_cover)
    )

# Aggregate percentages
#ms_line <- ggplot(ms_percent_cover_summary, aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover", x = "Date", y = "Mean Percent Cover")
#ms_line

# Percentages by zone
ms_line_facet <- ggplot(ms_percent_cover_summary, aes(x = date, y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover by Zone", x = "Date", y = "Mean Percent Cover") +
  facet_wrap(~Replicate_Zone)
ms_line_facet

# Percentages by zone of species present in seeedbank
ms_seed_only <- ggplot(filter(ms_percent_cover_summary, Species == "JUBU" | Species == "FEPE" | Species == "COSU" | Species == "ERCA" | Species == "LYHY" | Species == "SYSU" | Species == "BAPI" | Species == "PSBR" | Species == "SIBE" | Species == "SPSP" | Species == "POMO" | Species == "SOOL" | Species == "ZEMU" | Species == "CYER" | Species == "ERCA" | Species == "ERCO" | Species == "FRSA"), aes(x = factor(date), y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover of Seed Bank Species", x = "Date", y = "Mean Percent Cover", caption = "6/17 of seed bank species present; \n\ transition most species-rich; \n\ note SYSU") +
  facet_wrap(~Replicate_Zone)
ms_seed_only


# Percentages by zone of natives only
ms_native <- ggplot(filter(ms_percent_cover_summary, Native_Status == "N"), aes(x = factor(date), y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover of Natives by Zone", x = "Date", y = "Mean Percent Cover", caption = "Note JUPA, ERVA, HOBR, ELMA, ELGL, DISP, STPU") +
  facet_wrap(~Replicate_Zone)
ms_native

# Percentages by zone of exotics only
ms_exotic <- ggplot(filter(ms_percent_cover_summary, Native_Status == "E"), aes(x = factor(date), y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover of Exotics by Zone", x = "Date", y = "Mean Percent Cover", caption = "Note SOOL") +
  facet_wrap(~Replicate_Zone)
ms_exotic

# Central zone percentages
#ms_c_line <- filter(ms_percent_cover, Replicate_Zone == "C") %>% 
  #group_by(Species, date, Native_Status) %>% 
  #summarize(
  #  mean_percentage = mean(percent_cover)
  #  ) %>%
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Central Zone", x = "Date", y = "Mean Percent Cover")
#ms_c_line

# Transition zone percentages
#ms_t_line <- filter(ms_percent_cover, Replicate_Zone == "T") %>% 
  #group_by(Species, date, Native_Status) %>% 
  #summarize(
  #  mean_percentage = mean(percent_cover)
  #  ) %>%
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Transition Zone", x = "Date", y = "Mean Percent Cover")
#ms_t_line

# Upland zone percentages
#ms_u_line <- filter(ms_percent_cover, Replicate_Zone == "U") %>% 
  #group_by(Species, date, Native_Status) %>% 
  #summarize(
  #  mean_percentage = mean(percent_cover)
  #  ) %>%
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Transition Zone", x = "Date", y = "Mean Percent Cover")
#ms_u_line


# Aggregate percentages of 12 indicative species
#ms_12_line <- filter(ms_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover of 12 Indicative Species", x = "Date", y = "Mean Percent Cover")
#ms_12_line

# Aggregate percentages of 12 indicative species by zone
ms_12_line_facet <- filter(ms_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  ggplot(aes(x = factor(date), y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover of 12 Indicative Species by Zone", x = "Date", y = "Mean Percent Cover") +
  facet_wrap(~Replicate_Zone)
ms_12_line_facet

# Central zone percentages of 12 indicative species
#ms_c_12_line <- filter(ms_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  #filter(Replicate_Zone == "C") %>% 
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover of 12 Indicative Species in Central Zone", x = "Date", y = "Mean Percent Cover")
#ms_c_12_line

# Transition zone percentages of 12 indicative species
#ms_t_12_line <- filter(ms_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  #filter(Replicate_Zone == "T") %>% 
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover of 12 Indicative Species in Transition Zone", x = "Date", y = "Mean Percent Cover")
#ms_t_12_line

# Upland zone percentages of 12 indicative species
#ms_u_12_line <- filter(ms_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  #filter(Replicate_Zone == "U") %>% 
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover of 12 Indicative Species in Upland Zone", x = "Date", y = "Mean Percent Cover")
#ms_u_12_line


# Native vs. exotic
ms_native <- ms_percent_cover_summary %>% 
  group_by(Native_Status, date, Replicate_Zone) %>% 
  summarize(
    total = sum(mean_percentage)
  ) %>% 
  na.omit()

# Aggregate
#ms_native_line <- ggplot(ms_native, aes(x = date, y = total)) +
  #geom_line(aes(color = Native_Status, group = Native_Status)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover", x = "Date", y = "Mean Percent Cover")
#ms_native_line

# Aggregate by zone
ms_native_line_facet <- ggplot(ms_native, aes(x = factor(date), y = total)) +
  geom_line(aes(color = Native_Status, group = Native_Status)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Native vs Exotic total cover", x = "Date", y = "total Percent Cover", caption = "Natives increasing") +
  facet_wrap(~Replicate_Zone)
ms_native_line_facet

# Central zone
#ms_c_native_line <- ggplot(filter(ms_native, Replicate_Zone == "C"), aes(x = date, y = total)) +
  #geom_line(aes(color = Native_Status, group = Native_Status)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Central Zone", x = "Date", y = "Mean Percent Cover")
#ms_c_native_line

# Transition zone
#ms_t_native_line <- ggplot(filter(ms_native, Replicate_Zone == "T"), aes(x = date, y = total)) +
  #geom_line(aes(color = Native_Status, group = Native_Status)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Transition Zone", x = "Date", y = "Mean Percent Cover")
#ms_t_native_line

# Upland zone
#ms_u_native_line <- ggplot(filter(ms_native, Replicate_Zone == "U"), aes(x = date, y = total)) +
  #geom_line(aes(color = Native_Status, group = Native_Status)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Upland Zone", x = "Date", y = "Mean Percent Cover")
#ms_u_native_line

```

# Redtail

```{r echo = FALSE, message = FALSE, warning = FALSE}

# Aggregate RT data
rt_percent_cover_summary <- rt_percent_cover %>% 
  group_by(Species, date, Native_Status, Replicate_Zone) %>% 
  summarize(
    mean_percentage = mean(percent_cover)
    )

# Aggregate percentages
#rt_line <- ggplot(rt_percent_cover_summary, aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover", x = "Date", y = "Mean Percent Cover")
#rt_line

# Aggregate percentages by zone
rt_line_facet <- ggplot(rt_percent_cover_summary, aes(x = date, y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover by Zone", x = "Date", y = "Mean Percent Cover") +
  facet_wrap(~Replicate_Zone)
rt_line_facet

# Percentages by zone of species present in seeedbank
rt_seed_only <- ggplot(filter(rt_percent_cover_summary, Species == "JUBU" | Species == "POMO" | Species == "ERCA" | Species == "COSU" | Species == "SOOL" | Species == "SYSU" | Species == "SPSP" | Species == "BAPI" | Species == "EUSE" | Species == "FEPE" | Species == "POAN" | Species == "ZEMU"), aes(x = factor(date), y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover of Seed Bank Species", x = "Date", y = "Mean Percent Cover", caption = "9/12 of seed bank species present; \n\ transition most species-rich; \n\ note JUBU, POMO; \n\ note decreasing FEPE") +
  facet_wrap(~Replicate_Zone)
rt_seed_only


# Percentages by zone of natives only
rt_native <- ggplot(filter(rt_percent_cover_summary, Native_Status == "N"), aes(x = factor(date), y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover of Natives by Zone", x = "Date", y = "Mean Percent Cover", caption = "Note JUPH, JUBU, DISP, EPCA, STPU") +
  facet_wrap(~Replicate_Zone)
rt_native

# Percentages by zone of exotics only
rt_exotic <- ggplot(filter(rt_percent_cover_summary, Native_Status == "E"), aes(x = factor(date), y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover of Exotics by Zone", x = "Date", y = "Mean Percent Cover", caption = "Most exotics in upland; \n\ note UNKGRASS, ERCI, POMO") +
  facet_wrap(~Replicate_Zone)
rt_exotic

# Central zone percentages
#rt_c_line <- filter(rt_percent_cover, Replicate_Zone == "C") %>% 
  #group_by(Species, date, Native_Status) %>% 
  #summarize(
  #  mean_percentage = mean(percent_cover)
  #  ) %>%
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Central Zone", x = "Date", y = "Mean Percent Cover")
#rt_c_line

# Transition zone percentages
#rt_t_line <- filter(rt_percent_cover, Replicate_Zone == "T") %>% 
  #group_by(Species, date, Native_Status) %>% 
  #summarize(
  #  mean_percentage = mean(percent_cover)
  #  ) %>%
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Transition Zone", x = "Date", y = "Mean Percent Cover")
#rt_t_line

# Upland zone percentages
#rt_u_line <- filter(rt_percent_cover, Replicate_Zone == "U") %>% 
  #group_by(Species, date, Native_Status) %>% 
  #summarize(
  #  mean_percentage = mean(percent_cover)
  #  ) %>%
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Transition Zone", x = "Date", y = "Mean Percent Cover")
#rt_u_line


# Aggregate percentages of 12 indicative species
#rt_12_line <- filter(rt_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover of 12 Indicative Species", x = "Date", y = "Mean Percent Cover")
#rt_12_line

# Aggregate percentages of 12 indicative species by zone
rt_12_line_facet <- filter(rt_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  ggplot(aes(x = factor(date), y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover of 12 Indicative Species by Zone", x = "Date", y = "Mean Percent Cover", caption = "Note highly variable ELMA") +
  facet_wrap(~Replicate_Zone)
rt_12_line_facet

# Central zone percentages of 12 indicative species
#rt_c_12_line <- filter(rt_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  #filter(Replicate_Zone == "C") %>% 
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover of 12 Indicative Species in Central Zone", x = "Date", y = "Mean Percent Cover")
#rt_c_12_line

# Transition zone percentages of 12 indicative species
#rt_t_12_line <- filter(rt_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  #filter(Replicate_Zone == "T") %>% 
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover of 12 Indicative Species in Transition Zone", x = "Date", y = "Mean Percent Cover")
#rt_t_12_line

# Upland zone percentages of 12 indicative species
#rt_u_12_line <- filter(rt_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  #filter(Replicate_Zone == "U") %>% 
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover of 12 Indicative Species in Upland Zone", x = "Date", y = "Mean Percent Cover")
#rt_u_12_line


# Native vs. exotic
rt_native <- rt_percent_cover_summary %>% 
  group_by(Native_Status, date, Replicate_Zone) %>% 
  summarize(
    total = sum(mean_percentage)
  ) %>% 
  na.omit()

# Aggregate
#rt_native_line <- ggplot(rt_native, aes(x = date, y = total)) +
  #geom_line(aes(color = Native_Status, group = Native_Status)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover", x = "Date", y = "Mean Percent Cover")
#rt_native_line

# Aggregate by zone
rt_native_line_facet <- ggplot(rt_native, aes(x = factor(date), y = total)) +
  geom_line(aes(color = Native_Status, group = Native_Status)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover by Zone", x = "Date", y = "Mean Percent Cover", caption = "Note upward spike in central & transition vs downward dip in upland") +
  facet_wrap(~Replicate_Zone)
rt_native_line_facet

# Central zone
#rt_c_native_line <- ggplot(filter(rt_native, Replicate_Zone == "C"), aes(x = date, y = total)) +
  #geom_line(aes(color = Native_Status, group = Native_Status)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Central Zone", x = "Date", y = "Mean Percent Cover")
#rt_c_native_line

# Transition zone
#rt_t_native_line <- ggplot(filter(rt_native, Replicate_Zone == "T"), aes(x = date, y = total)) +
  #geom_line(aes(color = Native_Status, group = Native_Status)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Transition Zone", x = "Date", y = "Mean Percent Cover")
#rt_t_native_line

# Upland zone
#rt_u_native_line <- ggplot(filter(rt_native, Replicate_Zone == "U"), aes(x = date, y = total)) +
  #geom_line(aes(color = Native_Status, group = Native_Status)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Upland Zone", x = "Date", y = "Mean Percent Cover")
#rt_u_native_line

```

# Tadpole

```{r echo = FALSE, message = FALSE, warning = FALSE}

 # Aggregate TP data
tp_percent_cover_summary <- tp_percent_cover %>% 
  group_by(Species, date, Native_Status, Replicate_Zone) %>% 
  summarize(
    mean_percentage = mean(percent_cover)
    )

# Aggregate percentages
#tp_line <- ggplot(tp_percent_cover_summary, aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover", x = "Date", y = "Mean Percent Cover")
#tp_line

# Aggregate percentages by zone
tp_line_facet <- ggplot(tp_percent_cover_summary, aes(x = date, y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover by Zone", x = "Date", y = "Mean Percent Cover") +
  facet_wrap(~Replicate_Zone)
tp_line_facet

# Percentages by zone of species present in seeedbank
tp_seed_only <- ggplot(filter(tp_percent_cover_summary, Species == "JUBU" | Species == "COSU" | Species == "SPSP" | Species == "ERCA" | Species == "BAPI" | Species == "FEPE" | Species == "LACO" | Species == "SOOL" | Species == "EHER" | Species == "LYHY" | Species == "SYSU" | Species == "ANNU" | Species == "DIMI" | Species == "ELGL" | Species == "ELMA" | Species == "ERCO" | Species == "POMO" | Species == "SIBE" | Species == " ZEMU"), aes(x = factor(date), y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover of Seed Bank Species", x = "Date", y = "Mean Percent Cover", caption = "... of seed bank species present...") +
  facet_wrap(~Replicate_Zone)
tp_seed_only


# Percentages by zone of natives only
tp_native <- ggplot(filter(tp_percent_cover_summary, Native_Status == "N"), aes(x = factor(date), y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover of Natives by Zone", x = "Date", y = "Mean Percent Cover", caption = "...") +
  facet_wrap(~Replicate_Zone)
tp_native

# Percentages by zone of exotics only
tp_exotic <- ggplot(filter(tp_percent_cover_summary, Native_Status == "E"), aes(x = factor(date), y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover of Exotics by Zone", x = "Date", y = "Mean Percent Cover", caption = "...") +
  facet_wrap(~Replicate_Zone)
tp_exotic

# Central zone percentages
#tp_c_line <- filter(tp_percent_cover, Replicate_Zone == "C") %>% 
  #group_by(Species, date, Native_Status) %>% 
  #summarize(
  #  mean_percentage = mean(percent_cover)
  #  ) %>%
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Central Zone", x = "Date", y = "Mean Percent Cover")
#tp_c_line

# Transition zone percentages
#tp_t_line <- filter(tp_percent_cover, Replicate_Zone == "T") %>% 
  #group_by(Species, date, Native_Status) %>% 
  #summarize(
  #  mean_percentage = mean(percent_cover)
  #  ) %>%
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Transition Zone", x = "Date", y = "Mean Percent Cover")
#tp_t_line

# Upland zone percentages
#tp_u_line <- filter(tp_percent_cover, Replicate_Zone == "U") %>% 
  #group_by(Species, date, Native_Status) %>% 
  #summarize(
  #  mean_percentage = mean(percent_cover)
  #  ) %>%
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Transition Zone", x = "Date", y = "Mean Percent Cover")
#tp_u_line


# Aggregate percentages of 12 indicative species
#tp_12_line <- filter(tp_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover of 12 Indicative Species", x = "Date", y = "Mean Percent Cover")
#tp_12_line

# Aggregate percentages of 12 indicative species by zone
tp_12_line_facet <- filter(tp_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  ggplot(aes(x = factor(date), y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover of 12 Indicative Species by Zone", x = "Date", y = "Mean Percent Cover") +
  facet_wrap(~Replicate_Zone)
tp_12_line_facet

# Central zone percentages of 12 indicative species
#tp_c_12_line <- filter(tp_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  #filter(Replicate_Zone == "C") %>% 
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover of 12 Indicative Species in Central Zone", x = "Date", y = "Mean Percent Cover")
#tp_c_12_line

# Transition zone percentages of 12 indicative species
#tp_t_12_line <- filter(tp_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  #filter(Replicate_Zone == "T") %>% 
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover of 12 Indicative Species in Transition Zone", x = "Date", y = "Mean Percent Cover")
#tp_t_12_line

# Upland zone percentages of 12 indicative species
#tp_u_12_line <- filter(tp_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  #filter(Replicate_Zone == "U") %>% 
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover of 12 Indicative Species in Upland Zone", x = "Date", y = "Mean Percent Cover")
#tp_u_12_line


# Native vs. exotic
tp_native <- tp_percent_cover_summary %>% 
  group_by(Native_Status, date, Replicate_Zone) %>% 
  summarize(
    total = sum(mean_percentage)
  ) %>% 
  na.omit()

# Aggregate
#tp_native_line <- ggplot(tp_native, aes(x = date, y = total)) +
  #geom_line(aes(color = Native_Status, group = Native_Status)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover", x = "Date", y = "Mean Percent Cover")
#tp_native_line

# Aggregate by zone
tp_native_line_facet <- ggplot(tp_native, aes(x = factor(date), y = total)) +
  geom_line(aes(color = Native_Status, group = Native_Status)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover by Zone", x = "Date", y = "Mean Percent Cover") +
  facet_wrap(~Replicate_Zone)
tp_native_line_facet

# Central zone
#tp_c_native_line <- ggplot(filter(tp_native, Replicate_Zone == "C"), aes(x = date, y = total)) +
  #geom_line(aes(color = Native_Status, group = Native_Status)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Central Zone", x = "Date", y = "Mean Percent Cover")
#tp_c_native_line

# Transition zone
#tp_t_native_line <- ggplot(filter(tp_native, Replicate_Zone == "T"), aes(x = date, y = total)) +
  #geom_line(aes(color = Native_Status, group = Native_Status)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Transition Zone", x = "Date", y = "Mean Percent Cover")
#tp_t_native_line

# Upland zone
#tp_u_native_line <- ggplot(filter(tp_native, Replicate_Zone == "U"), aes(x = date, y = total)) +
  #geom_line(aes(color = Native_Status, group = Native_Status)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Upland Zone", x = "Date", y = "Mean Percent Cover")
#tp_u_native_line

```

# Whitetail 1

```{r echo = FALSE, message = FALSE, warning = FALSE}

# Aggregate WT1 data
wt1_percent_cover_summary <- wt1_percent_cover %>% 
  group_by(Species, date, Native_Status, Replicate_Zone) %>% 
  summarize(
    mean_percentage = mean(percent_cover)
    )

# Aggregate percentages
#wt1_line <- ggplot(wt1_percent_cover_summary, aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover", x = "Date", y = "Mean Percent Cover")
#wt1_line

# Aggregate percentages by zone
wt1_line_facet <- ggplot(wt1_percent_cover_summary, aes(x = date, y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover by Zone", x = "Date", y = "Mean Percent Cover") +
  facet_wrap(~Replicate_Zone)
wt1_line_facet

# Percentages by zone of species present in seeedbank
wt1_seed_only <- ggplot(filter(wt1_percent_cover_summary, Species == "JUBU" | Species == "COSU" | Species == "SPSP" | Species == "ERCA" | Species == "BAPI" | Species == "FEPE" | Species == "LACO" | Species == "SOOL" | Species == "EHER" | Species == "LYHY" | Species == "SYSU" | Species == "ANNU" | Species == "DIMI" | Species == "ELGL" | Species == "ELMA" | Species == "ERCO" | Species == "POMO" | Species == "SIBE" | Species == " ZEMU"), aes(x = factor(date), y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover of Seed Bank Species", x = "Date", y = "Mean Percent Cover", caption = "... of seed bank species present...") +
  facet_wrap(~Replicate_Zone)
wt1_seed_only


# Percentages by zone of natives only
wt1_native <- ggplot(filter(wt1_percent_cover_summary, Native_Status == "N"), aes(x = factor(date), y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover of Natives by Zone", x = "Date", y = "Mean Percent Cover", caption = "...") +
  facet_wrap(~Replicate_Zone)
wt1_native

# Percentages by zone of exotics only
wt1_exotic <- ggplot(filter(wt1_percent_cover_summary, Native_Status == "E"), aes(x = factor(date), y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover of Exotics by Zone", x = "Date", y = "Mean Percent Cover", caption = "...") +
  facet_wrap(~Replicate_Zone)
wt1_exotic

# Central zone percentages
#wt1_c_line <- filter(wt1_percent_cover, Replicate_Zone == "C") %>% 
  #group_by(Species, date, Native_Status) %>% 
  #summarize(
  #  mean_percentage = mean(percent_cover)
  #  ) %>%
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Central Zone", x = "Date", y = "Mean Percent Cover")
#wt1_c_line

# Transition zone percentages
#wt1_t_line <- filter(wt1_percent_cover, Replicate_Zone == "T") %>% 
  #group_by(Species, date, Native_Status) %>% 
  #summarize(
  #  mean_percentage = mean(percent_cover)
  #  ) %>%
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Transition Zone", x = "Date", y = "Mean Percent Cover")
#wt1_t_line

# Upland zone percentages
#wt1_u_line <- filter(wt1_percent_cover, Replicate_Zone == "U") %>% 
  #group_by(Species, date, Native_Status) %>% 
  #summarize(
  #  mean_percentage = mean(percent_cover)
  #  ) %>%
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Transition Zone", x = "Date", y = "Mean Percent Cover")
#wt1_u_line


# Aggregate percentages of 12 indicative species
#wt1_12_line <- filter(wt1_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover of 12 Indicative Species", x = "Date", y = "Mean Percent Cover")
#wt1_12_line

# Aggregate percentages of 12 indicative species
wt1_12_line_facet <- filter(wt1_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  ggplot(aes(x = factor(date), y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover of 12 Indicative Species by Zone", x = "Date", y = "Mean Percent Cover") +
  facet_wrap(~Replicate_Zone)
wt1_12_line_facet

# Central zone percentages of 12 indicative species
#wt1_c_12_line <- filter(wt1_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  #filter(Replicate_Zone == "C") %>% 
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover of 12 Indicative Species in Central Zone", x = "Date", y = "Mean Percent Cover")
#wt1_c_12_line

# Transition zone percentages of 12 indicative species
#wt1_t_12_line <- filter(wt1_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  #filter(Replicate_Zone == "T") %>% 
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover of 12 Indicative Species in Transition Zone", x = "Date", y = "Mean Percent Cover")
#wt1_t_12_line

# Upland zone percentages of 12 indicative species
#wt1_u_12_line <- filter(wt1_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  #filter(Replicate_Zone == "U") %>% 
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover of 12 Indicative Species in Upland Zone", x = "Date", y = "Mean Percent Cover")
#wt1_u_12_line


# Native vs. exotic
wt1_native <- wt1_percent_cover_summary %>% 
  group_by(Native_Status, date, Replicate_Zone) %>% 
  summarize(
    total = sum(mean_percentage)
  ) %>% 
  na.omit()

# Aggregate
#wt1_native_line <- ggplot(wt1_native, aes(x = date, y = total)) +
  #geom_line(aes(color = Native_Status, group = Native_Status)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover", x = "Date", y = "Mean Percent Cover")
#wt1_native_line

# Aggregate by Zone
wt1_native_line_facet <- ggplot(wt1_native, aes(x = factor(date), y = total)) +
  geom_line(aes(color = Native_Status, group = Native_Status)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover by Zone", x = "Date", y = "Mean Percent Cover") +
  facet_wrap(~Replicate_Zone)
wt1_native_line_facet

# Central zone
#wt1_c_native_line <- ggplot(filter(wt1_native, Replicate_Zone == "C"), aes(x = date, y = total)) +
  #geom_line(aes(color = Native_Status, group = Native_Status)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Central Zone", x = "Date", y = "Mean Percent Cover")
#wt1_c_native_line

# Transition zone
#wt1_t_native_line <- ggplot(filter(wt1_native, Replicate_Zone == "T"), aes(x = date, y = total)) +
  #geom_line(aes(color = Native_Status, group = Native_Status)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Transition Zone", x = "Date", y = "Mean Percent Cover")
#wt1_t_native_line

# Upland zone
#wt1_u_native_line <- ggplot(filter(wt1_native, Replicate_Zone == "U"), aes(x = date, y = total)) +
  #geom_line(aes(color = Native_Status, group = Native_Status)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Upland Zone", x = "Date", y = "Mean Percent Cover")
#wt1_u_native_line

```

# Whitetail 2

```{r echo = FALSE, message = FALSE, warning = FALSE}

# Aggregate WT2 data
wt2_percent_cover_summary <- wt2_percent_cover %>% 
  group_by(Species, date, Native_Status, Replicate_Zone) %>% 
  summarize(
    mean_percentage = mean(percent_cover)
    )

# Aggregate percentages
#wt2_line <- ggplot(wt2_percent_cover_summary, aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover", x = "Date", y = "Mean Percent Cover")
#wt2_line

# Aggregate percentages by zone
wt2_line_facet <- ggplot(wt2_percent_cover_summary, aes(x = date, y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover by Zone", x = "Date", y = "Mean Percent Cover") +
  facet_wrap(~Replicate_Zone)
wt2_line_facet

# Percentages by zone of species present in seeedbank
wt2_seed_only <- ggplot(filter(wt2_percent_cover_summary, Species == "JUBU" | Species == "COSU" | Species == "SPSP" | Species == "ERCA" | Species == "BAPI" | Species == "FEPE" | Species == "LACO" | Species == "SOOL" | Species == "EHER" | Species == "LYHY" | Species == "SYSU" | Species == "ANNU" | Species == "DIMI" | Species == "ELGL" | Species == "ELMA" | Species == "ERCO" | Species == "POMO" | Species == "SIBE" | Species == " ZEMU"), aes(x = factor(date), y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover of Seed Bank Species", x = "Date", y = "Mean Percent Cover", caption = "... of seed bank species present...") +
  facet_wrap(~Replicate_Zone)
wt2_seed_only


# Percentages by zone of natives only
wt2_native <- ggplot(filter(wt2_percent_cover_summary, Native_Status == "N"), aes(x = factor(date), y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover of Natives by Zone", x = "Date", y = "Mean Percent Cover", caption = "...") +
  facet_wrap(~Replicate_Zone)
wt2_native

# Percentages by zone of exotics only
wt2_exotic <- ggplot(filter(wt2_percent_cover_summary, Native_Status == "E"), aes(x = factor(date), y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover of Exotics by Zone", x = "Date", y = "Mean Percent Cover", caption = "...") +
  facet_wrap(~Replicate_Zone)
wt2_exotic

# Central zone percentages
#wt2_c_line <- filter(wt2_percent_cover, Replicate_Zone == "C") %>% 
  #group_by(Species, date, Native_Status) %>% 
  #summarize(
  #  mean_percentage = mean(percent_cover)
  #  ) %>%
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Central Zone", x = "Date", y = "Mean Percent Cover")
#wt2_c_line

# Transition zone percentages
#wt2_t_line <- filter(wt2_percent_cover, Replicate_Zone == "T") %>% 
  #group_by(Species, date, Native_Status) %>% 
  #summarize(
  #  mean_percentage = mean(percent_cover)
  #  ) %>%
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Transition Zone", x = "Date", y = "Mean Percent Cover")
#wt2_t_line

# Upland zone percentages
#wt2_u_line <- filter(wt2_percent_cover, Replicate_Zone == "U") %>% 
  #group_by(Species, date, Native_Status) %>% 
  #summarize(
  #  mean_percentage = mean(percent_cover)
  #  ) %>%
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Transition Zone", x = "Date", y = "Mean Percent Cover")
#wt2_u_line


# Aggregate percentages of 12 indicative species
#wt2_12_line <- filter(wt2_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover of 12 Indicative Species", x = "Date", y = "Mean Percent Cover")
#wt2_12_line

# Aggregate percentages of 12 indicative species by zone
wt2_12_line_facet <- filter(wt2_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  ggplot(aes(x = factor(date), y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover of 12 Indicative Species by Zone", x = "Date", y = "Mean Percent Cover") +
  facet_wrap(~Replicate_Zone)
wt2_12_line_facet

# Central zone percentages of 12 indicative species
#wt2_c_12_line <- filter(wt2_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  #filter(Replicate_Zone == "C") %>% 
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover of 12 Indicative Species in Central Zone", x = "Date", y = "Mean Percent Cover")
#wt2_c_12_line

# Transition zone percentages of 12 indicative species
#wt2_t_12_line <- filter(wt2_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  #filter(Replicate_Zone == "T") %>% 
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover of 12 Indicative Species in Transition Zone", x = "Date", y = "Mean Percent Cover")
#wt2_t_12_line

# Upland zone percentages of 12 indicative species
#wt2_u_12_line <- filter(wt2_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  #filter(Replicate_Zone == "U") %>% 
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover of 12 Indicative Species in Upland Zone", x = "Date", y = "Mean Percent Cover")
#wt2_u_12_line


# Native vs. exotic
wt2_native <- wt2_percent_cover_summary %>% 
  group_by(Native_Status, date, Replicate_Zone) %>% 
  summarize(
    total = sum(mean_percentage)
  ) %>% 
  na.omit()

# Aggregate
#wt2_native_line <- ggplot(wt2_native, aes(x = date, y = total)) +
  #geom_line(aes(color = Native_Status, group = Native_Status)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover", x = "Date", y = "Mean Percent Cover")
#wt2_native_line

# Aggregate by zone
wt2_native_line_facet <- ggplot(wt2_native, aes(x = factor(date), y = total)) +
  geom_line(aes(color = Native_Status, group = Native_Status)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover by Zone", x = "Date", y = "Mean Percent Cover") +
  facet_wrap(~Replicate_Zone)
wt2_native_line_facet

# Central zone
#wt2_c_native_line <- ggplot(filter(wt2_native, Replicate_Zone == "C"), aes(x = date, y = total)) +
  #geom_line(aes(color = Native_Status, group = Native_Status)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Central Zone", x = "Date", y = "Mean Percent Cover")
#wt2_c_native_line

# Transition zone
#wt2_t_native_line <- ggplot(filter(wt2_native, Replicate_Zone == "T"), aes(x = date, y = total)) +
  #geom_line(aes(color = Native_Status, group = Native_Status)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Transition Zone", x = "Date", y = "Mean Percent Cover")
#wt2_t_native_line

# Upland zone
#wt2_u_native_line <- ggplot(filter(wt2_native, Replicate_Zone == "U"), aes(x = date, y = total)) +
  #geom_line(aes(color = Native_Status, group = Native_Status)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Upland Zone", x = "Date", y = "Mean Percent Cover")
#wt2_u_native_line

```

# Creekside

```{r echo = FALSE, message = FALSE, warning = FALSE}

# Aggregate CS data
cs_percent_cover_summary <- cs_percent_cover %>% 
  group_by(Species, date, Native_Status, Replicate_Zone) %>% 
  summarize(
    mean_percentage = mean(percent_cover)
    )

# Aggregate percentages
#cs_line <- ggplot(cs_percent_cover_summary, aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover", x = "Date", y = "Mean Percent Cover")
#cs_line

# Aggregate percentages by zone
cs_line_facet <- ggplot(cs_percent_cover_summary, aes(x = date, y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover by Zone", x = "Date", y = "Mean Percent Cover") +
  facet_wrap(~Replicate_Zone)
cs_line_facet

# Percentages by zone of species present in seeedbank
cs_seed_only <- ggplot(filter(cs_percent_cover_summary, Species == "JUBU" | Species == "COSU" | Species == "SPSP" | Species == "ERCA" | Species == "BAPI" | Species == "FEPE" | Species == "LACO" | Species == "SOOL" | Species == "EHER" | Species == "LYHY" | Species == "SYSU" | Species == "ANNU" | Species == "DIMI" | Species == "ELGL" | Species == "ELMA" | Species == "ERCO" | Species == "POMO" | Species == "SIBE" | Species == " ZEMU"), aes(x = factor(date), y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover of Seed Bank Species", x = "Date", y = "Mean Percent Cover", caption = "... of seed bank species present...") +
  facet_wrap(~Replicate_Zone)
cs_seed_only


# Percentages by zone of natives only
cs_native <- ggplot(filter(cs_percent_cover_summary, Native_Status == "N"), aes(x = factor(date), y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover of Natives by Zone", x = "Date", y = "Mean Percent Cover", caption = "...") +
  facet_wrap(~Replicate_Zone)
cs_native

# Percentages by zone of exotics only
cs_exotic <- ggplot(filter(cs_percent_cover_summary, Native_Status == "E"), aes(x = factor(date), y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover of Exotics by Zone", x = "Date", y = "Mean Percent Cover", caption = "...") +
  facet_wrap(~Replicate_Zone)
cs_exotic

# Central zone percentages
#cs_c_line <- filter(cs_percent_cover, Replicate_Zone == "C") %>% 
  #group_by(Species, date, Native_Status) %>% 
  #summarize(
  #  mean_percentage = mean(percent_cover)
  #  ) %>%
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Central Zone", x = "Date", y = "Mean Percent Cover")
#cs_c_line

# Transition zone percentages
#cs_t_line <- filter(cs_percent_cover, Replicate_Zone == "T") %>% 
  #group_by(Species, date, Native_Status) %>% 
  #summarize(
  #  mean_percentage = mean(percent_cover)
  #  ) %>%
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Transition Zone", x = "Date", y = "Mean Percent Cover")
#cs_t_line

# Upland zone percentages
#cs_u_line <- filter(cs_percent_cover, Replicate_Zone == "U") %>% 
  #group_by(Species, date, Native_Status) %>% 
  #summarize(
  #  mean_percentage = mean(percent_cover)
  #  ) %>%
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Transition Zone", x = "Date", y = "Mean Percent Cover")
#cs_u_line


# Aggregate percentages of 12 indicative species
#cs_12_line <- filter(cs_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover of 12 Indicative Species", x = "Date", y = "Mean Percent Cover")
#cs_12_line

# Aggregate percentages of 12 indicative species by zone
cs_12_line_facet <- filter(cs_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  ggplot(aes(x = factor(date), y = mean_percentage)) +
  geom_line(aes(color = Species, group = Species)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover of 12 Indicative Species by Zone", x = "Date", y = "Mean Percent Cover") +
  facet_wrap(~Replicate_Zone)
cs_12_line_facet

# Central zone percentages of 12 indicative species
#cs_c_12_line <- filter(cs_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  #filter(Replicate_Zone == "C") %>% 
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover of 12 Indicative Species in Central Zone", x = "Date", y = "Mean Percent Cover")
#cs_c_12_line

# Transition zone percentages of 12 indicative species
#cs_t_12_line <- filter(cs_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  #filter(Replicate_Zone == "T") %>% 
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover of 12 Indicative Species in Transition Zone", x = "Date", y = "Mean Percent Cover")
#cs_t_12_line

# Upland zone percentages of 12 indicative species
#cs_u_12_line <- filter(cs_percent_cover_summary, Species == "ERVA" | Species == "ERAR" | Species == "PSBR" | Species == "ELAC" | Species == "ELMA" | Species == "PLUN" | Species == "ALSA" | Species == "CRAQ" | Species == "HOBR" | Species == "PHEL" | Species == "CEMI") %>% 
  #filter(Replicate_Zone == "U") %>% 
  #ggplot(aes(x = date, y = mean_percentage)) +
  #geom_line(aes(color = Species, group = Species)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover of 12 Indicative Species in Upland Zone", x = "Date", y = "Mean Percent Cover")
#cs_u_12_line


# Native vs. exotic
cs_native <- cs_percent_cover_summary %>% 
  group_by(Native_Status, date, Replicate_Zone) %>% 
  summarize(
    total = sum(mean_percentage)
  ) %>% 
  na.omit()

# Aggregate
#cs_native_line <- ggplot(cs_native, aes(x = date, y = total)) +
  #geom_line(aes(color = Native_Status, group = Native_Status)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover", x = "Date", y = "Mean Percent Cover")
#cs_native_line

# Aggregate by zone
cs_native_line_facet <- ggplot(cs_native, aes(x = factor(date), y = total)) +
  geom_line(aes(color = Native_Status, group = Native_Status)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Percent Cover by Zone", x = "Date", y = "Mean Percent Cover") +
  facet_wrap(~Replicate_Zone)
cs_native_line_facet

# Central zone
#cs_c_native_line <- ggplot(filter(cs_native, Replicate_Zone == "C"), aes(x = date, y = total)) +
  #geom_line(aes(color = Native_Status, group = Native_Status)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Central Zone", x = "Date", y = "Mean Percent Cover")
#cs_c_native_line

# Transition zone
#cs_t_native_line <- ggplot(filter(cs_native, Replicate_Zone == "T"), aes(x = date, y = total)) +
  #geom_line(aes(color = Native_Status, group = Native_Status)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Transition Zone", x = "Date", y = "Mean Percent Cover")
#cs_t_native_line

# Upland zone
#cs_u_native_line <- ggplot(filter(cs_native, Replicate_Zone == "U"), aes(x = date, y = total)) +
  #geom_line(aes(color = Native_Status, group = Native_Status)) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #labs(title = "Percent Cover in Upland Zone", x = "Date", y = "Mean Percent Cover")
#cs_u_native_line

```

